version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./db/01.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - roinvesting
    healthcheck:
      test: ["CMD", "mysql", "-U", "strapi_roinvesting", "--password=admin"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  mysql-volume:
    name: roinvesting-mysql-volume
    driver: local

networks:
  roinvesting:
    driver: bridge
